services:
  backend:
    build:
      context: ./backend
    container_name: iot-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: iot-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend